services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - '18080:8080'
      - '50000:50000'
    volumes:
      - ./jenkins_data:/var/jenkins_home
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2000M